# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-04-29 05:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('client', 'client'), ('kitchen', 'kitchen')], max_length=7, verbose_name='Тип чека')),
                ('order', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Информация о заказе')),
                ('status', models.CharField(choices=[('new', 'new'), ('rendered', 'rendered'), ('printed', 'printed')], default='new', max_length=8, verbose_name='Статус чека')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf/', verbose_name='PDF-файл')),
            ],
            options={
                'verbose_name': 'Чек',
                'verbose_name_plural': 'Чеки',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название принтера')),
                ('api_key', models.CharField(max_length=250, unique=True, verbose_name='Ключ доступа к API')),
                ('check_type', models.CharField(choices=[('client', 'client'), ('kitchen', 'kitchen')], max_length=7, verbose_name='Тип чека')),
                ('point_id', models.IntegerField(verbose_name='Точка привязки принтера')),
            ],
            options={
                'verbose_name': 'Принтер',
                'verbose_name_plural': 'Принтеры',
            },
        ),
        migrations.AddField(
            model_name='check',
            name='printer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checks.Printer', verbose_name='Принтер'),
        ),
    ]
